# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"  # if you want to concentrate on pull request for only direct dependencies
      - dependency-type: "production"  # if you want only dependencies in the "Product dependency group"
    #Use assignees to specify individual assignees for all pull requests raised for a package manager including security updates
    assignees:
      - "clchandan"
